### ISSUE TITLE
sshscan: Reads don't time out

### ISSUE THREAD

**Issue by Matir** [Matir/hacks#2]
Workers just get stuck in read...

**Comment by Matir** [comment]
```
goroutine 16 [IO wait, 1071 minutes]:
internal/poll.runtime_pollWait(0x7f89f67c1590, 0x72, 0x7a9840)
        /usr/lib/go-1.15/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000238c98, 0x72, 0x7a9800, 0x90d0f0, 0x0)
        /usr/lib/go-1.15/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go-1.15/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000238c80, 0xc0003f6b0a, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.15/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000238c80, 0xc0003f6b0a, 0x1, 0x1, 0xc, 0x0, 0x0)
        /usr/lib/go-1.15/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000098058, 0xc0003f6b0a, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.15/src/net/net.go:182 +0x8e
main.(*ConnLogger).Read(0xc0002ced80, 0xc0003f6b0a, 0x1, 0x1, 0xc0001adb18, 0x4158d8, 0x1)
        /home/david/Projects/hacks/go/sshscan/connlog.go:25 +0x5b
io.ReadAtLeast(0x7f89f67c38c0, 0xc0002ced80, 0xc0003f6b0a, 0x1, 0x1, 0x1, 0xc0003f6b00, 0xc0001adba8, 0x62b23a)
        /usr/lib/go-1.15/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/lib/go-1.15/src/io/io.go:333
golang.org/x/crypto/ssh.readVersion(0x7f89f67c38c0, 0xc0002ced80, 0xc0002ced80, 0x7f89f67c38c0, 0xc0002ced80, 0x0, 0x0)
        /home/david/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5/ssh/transport.go:317 +0x105
golang.org/x/crypto/ssh.exchangeVersions(0x7f89f67c3898, 0xc0002ced80, 0xc0003f6b00, 0xa, 0xa, 0x10, 0x9, 0x10, 0x8, 0xc0001adc80)
        /home/david/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5/ssh/transport.go:301 +0x15d
golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc00024d480, 0xc00037da00, 0x10, 0xc0002c20d0, 0x0, 0x0)
        /home/david/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5/ssh/client.go:100 +0xf2
golang.org/x/crypto/ssh.NewClientConn(0x7ade00, 0xc0002ced80, 0xc00037da00, 0x10, 0xc0001addd8, 0x7adec0, 0xc000098058, 0x0, 0x0, 0x7f8a23cb97d0, ...)
        /home/david/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5/ssh/client.go:83 +0x117
main.(*HostScanner).scanOne(0xc000506690, 0x0, 0x0)
        /home/david/Projects/hacks/go/sshscan/sshscan.go:102 +0x2f3
main.(*HostScanner).Scan(0xc000506690, 0xc000506690, 0xd)
        /home/david/Projects/hacks/go/sshscan/sshscan.go:120 +0xcf
main.(*Worker).Run(0xc000012b40)
        /home/david/Projects/hacks/go/sshscan/worker.go:32 +0x19f
created by main.main
        /home/david/Projects/hacks/go/sshscan/main.go:54 +0x2a6
```
